secretsPaths:
  gigachat:
    cert: ../cert/cert.pem
    key: ../cert/private.key
  certChain: ../cert/cacrt

token:
  gigachat: 
  telegram:   # Получить у @BotFather

# Настройки бота
bot:
  summary_time: "13:00"  # Время отправки сводки (24-часовой формат)
  max_messages_per_group: 100  # Максимальное количество сообщений для анализа из каждой группы
  summary_language: "ru"  # Язык сводки

# Конфигурация групп и топиков
groups:
  # # Пример обычной группы
  # - id: -1234567890123  # ID группы
  #   name: "Обычная группа"  # Название для отображения
  #   topics: []  # Пустой список для обычных групп
    
  # Пример мультигруппы с топиками
  - id: -1002846307143  # ID мультигруппы
    name: "Мультигруппа с топиками"
    topics:
      - id: 2  # message_thread_id топика
        name: "1. 💼 | Кредитный фронт"
      - id: 7
        name: "2. 💰 | Касса & Операции"
      - id: 10
        name: "3. 🛡 | Безопасность & Фрод"
      - id: 14
        name: "4. 📈 | Инвестиции & VIP"
