version: '3.8'

services:
  telegram-summary-bot:
    build: .
    container_name: telegram_summary_bot
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
    restart: unless-stopped
    volumes:
      - .:/app
      - bot_data:/app/data

volumes:
  bot_data:

